name: libpymcr

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]
  workflow_dispatch:

concurrency :
  group: ${{ github.workflow }}-${{ github.ref == 'refs/head/main' && github.run_number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  build_and_test:
    name: Build and test, ${{ matrix.variant.os }}, py${{ matrix.pyvariant.version }}
    runs-on: ${{ matrix.variant.os }}
    # Matlab only provides binaries for 64-bit systems - so force x86_64 builds
    strategy:
      fail-fast: false
      matrix:
        variant:
          - {os: ubuntu-22.04, matlab-version: R2020a, tag: manylinux_x86_64, mlprefix: /host/,
             mltag: glnxa64, zpsuf: .zip, python_shell: 'bash -l {0}'}
          - {os: macos-12, matlab-version: R2020a, tag: macosx_x86_64, mlprefix: '',
             mltag: maci64, zpsuf: .dmg.zip, python_shell: 'bash -l {0}'}
          - {os: windows-2022, matlab-version: R2021a, tag: win_amd64, mlprefix: '',
             mltag: win64, zpsuf: .zip, python_shell: 'powershell'}
        pyvariant:
          - {version: '3.8', tag: cp38}
    env:
      # MCRVER and MCRV must agree (R2020a is v98, R2022b is v913 etc)
      MCRVER: R2020a

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up MATLAB
        if: ${{ matrix.variant.os == 'ubuntu-22.04' }}
        uses: matlab-actions/setup-matlab@v1.2.4
        with:
          release: ${{ matrix.variant.matlab-version }}
      - name: Cache MCR
        if: ${{ matrix.variant.os != 'ubuntu-22.04' }}
        id: cache-mcr
        uses: actions/cache@v3
        with:
          path: mcr
          key: ${{ runner.os }}-matlab-${{ env.MCRVER }}-mcr
      - name: Setup directories
        run: |
          mkdir -p mcr 
          pip3 install requests
          python3 gist_test_ctf.py --get --token=${{ secrets.GH_GIST_TOKEN }}
          echo "HOSTDIRECTORY=`pwd`" >> $GITHUB_ENV
          if which matlab; then
            echo "MATLABEXECUTABLE=`which matlab`" >> $GITHUB_ENV;
          else
            echo "MATLABEXECUTABLE=`pwd`/mcr/bin/matlab" >> $GITHUB_ENV;
          fi
      - name: Install Mac MCR
        if: ${{ matrix.variant.os == 'macos-12' && steps.cache-mcr.outputs.cache-hit != 'true' }}
        run: |
          unzip -d . -q test/pace_neutrons_installer.zip
          sudo ./pace_neutrons_installer/Contents/MacOS/setup -mode silent -agreeToLicense yes
          sleep 10
          while [[ ! -z $(ps aux |grep installer | grep mathworks) ]]; do sleep 10; done
          cp -r /Applications/MATLAB/MATLAB_Runtime/v98/* mcr/
      - name: Install Win MCR
        if: ${{ matrix.variant.os == 'windows-2022' && steps.cache-mcr.outputs.cache-hit != 'true' }}
        run: |
          powershell -Command "test\pace_neutrons_installer.exe -mode silent -agreeToLicense yes"
          sleep 10
          powershell -Command "while(Get-Process pace_neutrons_installer -ErrorAction SilentlyContinue) { Start-Sleep -Seconds 10 }"
          cp -r /c/Program\ Files/MATLAB/MATLAB\ Runtime/v98/* mcr/
      - name: Build wheel
        uses: pypa/cibuildwheel@v2.12.0
        env:
          CIBW_BUILD: ${{ matrix.pyvariant.tag }}-${{ matrix.variant.tag }}
          CIBW_ENVIRONMENT: >-
            MATLABEXECUTABLE="${{ matrix.variant.mlprefix }}${{ env.MATLABEXECUTABLE }}"
            HOSTDIRECTORY="${{ matrix.variant.mlprefix }}${{ env.HOSTDIRECTORY }}"
          CIBW_BUILD_VERBOSITY: 1
          MACOSX_DEPLOYMENT_TARGET: "10.15"
      - name: Setup micromamba environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          micromamba-version: "1.1.0"
          environment-file: false
          environment-name: libpymcr-test
          channels: conda-forge
          extra-specs: |
            python=${{ matrix.pyvariant.version }}
            numpy
            six
      - name: Install wheel and run test
        if: ${{ matrix.variant.os != 'macos-12' }}
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            # On Windows, micromamba only sets up for powershell
            conda init
            source ~/.bashrc
            conda activate libpymcr-test
          fi
          python -m pip install wheelhouse/*
          cd test
          python run_test.py
      - name: Setup tmate
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.variant.os }}_artifacts.zip
          path: |
            wheelhouse/*
            *.mex*
